### ISSUE TITLE
Can't follow Linux build instructions

### ISSUE THREAD

**Issue by StarsoftAnalysis** [rogerdahl/striprouter#3] opened 2019-03-30 14:15 UTC
I couldn't begin to try to build this excellent-looking project on Linux because the instructions don't seem to make sense.
Having git-cloned it, I can't `cd` into either `striploader/libraries/build` or `striploader/build` because those directories don't exist.
Please can you give me a clue to to get started?

**Comment by rogerdahl** [comment] 2019-04-01 21:21
I've updated and simplified the build and instructions. Do a `git pull` and give it a try!

Make sure you also do the "apt get" part of the install again, as I've added some more dependencies.

**Comment by StarsoftAnalysis** [comment] 2019-04-06 11:51
Thanks for that -- I've managed to build it now.

But not to run it.  I'm trying to use it on Arch Linux, and I realise that your instructions are for Debianesque distros, but perhaps you can help.  This is the error I get:

    $ ./striprouter
    Shader shader/vert error:
    
    Fatal error: Could not initialize NanoVG!
    terminate called without an active exception
    Aborted (core dumped)

I've tried searching for those error messages, but found nothing helpful.  I'd guess that this is an issue with mismatched versions of libraries, but I'm not sure where to start looking.

Cheers

Chris

**Comment by rogerdahl** [comment] 2019-04-09 17:29
Hi Chris, which version of OpenGL does your machine support? Striprouter requires OpenGL 3.3. You can check with

    glxinfo | grep 'version'

**Comment by StarsoftAnalysis** [comment] 2019-04-11 20:09
I seem to have OpenGL 3.3: 

    $ glxinfo | grep version
    server glx version string: 1.4
    client glx version string: 1.4
    GLX version: 1.4
    OpenGL core profile version string: 3.3.0 NVIDIA 340.107
    OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
    OpenGL version string: 3.3.0 NVIDIA 340.107
    OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
    OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.107 340.107
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
    server glx version string: 1.4
    client glx version string: 1.4
    GLX version: 1.4
    OpenGL core profile version string: 3.3.0 NVIDIA 340.107
    OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
    OpenGL version string: 3.3.0 NVIDIA 340.107
    OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
    OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.107 340.107
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00

glxdemo and glxgears work OK, if that's any help.

**Comment by rogerdahl** [comment] 2019-04-11 21:18
That looks like it should work. Striprouter specifically sets up OpenGL 3.3 in `main.cpp` and the shaders. Can you see if NanoGUI works for you? For me, getting a NanoGUI example up and running is:

```
$ git clone --recursive https://github.com/wjakob/nanogui.git
$ cd nanogui
$ cmake .
$ make
$ ./example1
```

**Comment by StarsoftAnalysis** [comment] 2019-04-12 10:43
That all works with no problems.

**Comment by rogerdahl** [comment] 2019-04-12 18:39
Can you try to change these lines:

https://github.com/rogerdahl/striprouter/blob/master/src/main.cpp#L158-L163

To:

```
    : nanogui::Screen(
          IntPos(windowW, windowH), "Stripboard Autorouter")
```

**Comment by StarsoftAnalysis** [comment] 2019-04-15 18:57
That makes no difference, I'm afraid -- I still get 

    $ ./striprouter
    Shader shader/vert error:
    
    Fatal error: Could not initialize NanoVG!
    terminate called without an active exception
    Aborted (core dumped)

I've tried to search for those errors messages, but I couldn't find anything helpful.

**Comment by rogerdahl** [comment] 2019-04-15 21:13
What's your exact OS? I'll try to reproduce it.

**Comment by StarsoftAnalysis** [comment] 2019-04-15 21:34
`Linux tui 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux`, i.e. Arch Linux running on an ageing Dell PC, with Intel 950 graphics.

I'll try installing it on my laptop, which is a Lenovo G50, also running Arch Linux.

**Comment by rogerdahl** [comment] 2019-04-15 21:48
Your `glxinfo` showed `NVIDIA 340.107`, not `Intel 950`. Is there also an NVIDIA card in your PC? If so, maybe it's just trying to start on the wrong card?

**Comment by StarsoftAnalysis** [comment] 2019-04-15 22:37
Good question re which card it's using -- I'll check tomorrow.

Meanwhile, I've compiled it on my Arch Linux laptop and it works!  Excellent -- now I can start playing...

**Comment by StarsoftAnalysis** [comment] 2019-04-18 11:35
`dmidecode` misled me about the graphics card.  X11 is using an Nvidia Quadro NVS 290, with two displays attached, and XFCE windowing.  `striprouter` gives the same error on either display.

**Comment by rogerdahl** [comment] 2019-04-18 22:43
I see the card has only 256 MB. I wonder if it's running out of memory. Before initializing NanoGUI, which in turn initializes NanoVG, Striprouter does allocate some resources on the graphics card, including around 5 textures for holding fonts, and some buffers and shaders.

Since it's such an old card and machine, I think you're out of luck, unless you'd like to dive in and start tinkering. I think I'd try reducing the fonts to some tiny size first, since that requires much smaller textures. You can do that by searching for `FONT_SIZE` in the `striprouter/src` dir and reducing all the values to a tenth of what they're now. For instance, in these ones, in `main.cpp`:

https://github.com/rogerdahl/striprouter/blob/4d3b18f696f4ea973dcca9302ebcaddb416a3789/src/main.cpp#L43-L46

**Comment by StarsoftAnalysis** [comment] 2019-04-21 10:21
I tried toying with font sizes, but it made no difference.  As you say, it's probably my ageing computer that's the problem.

Meanwhile, on my laptop, I've created a layout for my V-plotter, with an ESP8266 and two DRV8834 boards:

[vplot02.circuit.txt](https://github.com/rogerdahl/striprouter/files/3101103/vplot02.circuit.txt)

**Comment by rogerdahl** [comment] 2019-04-22 03:57
Nice!

I fixed a bug a couple of weeks ago that caused the printed sheet for the copper strip cuts to be misaligned, so that the cuts showed on the strip next to the ones they should show. I'm not sure if that was before or after you pulled your version, so you might want to pull the current version before doing the cuts.

The program supports dragging the components with the mouse so I usually try moving the components closer together to see if a complete route can still be found. So I tried that with yours, and it's possible to put the ESP8266 closer to the drivers if you want to use a smaller board.

If you move the components, you can write the new positions back to the `.circuit` file with the Save to .circuit button.

I'll go ahead and close this now. Feel free to open a ticket if you have feedback or questions :)

**Closed by rogerdahl** 2019-04-22 03:57 UTC

**Comment by rogerdahl** [comment] 2019-04-22 04:00
Oh and you can also model the sockets as separate rows if you're using modules and will be plugging them into sockets. That way, the router will be able to use the area under the sockets and probably save even more room.
